name:                ftr
version:             0.1.0.0
github:              "git@github.com:PaulAtTUBS/FeatureTraceRecording.git"
license:             BSD3
author:              "Paul Bittner"
maintainer:          "paul.bittner@uni-ulm.de"
copyright:           "2020 Paul Bittner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/PaulAtTUBS/FeatureTraceRecording#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- containers >= 0.6.2.1

library:
  source-dirs:
    - src
    - src/feature
    - src/tree
    - src/propositions

executables:
  ftr-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ftr

tests:
  ftr-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ftr
